Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/mqa887/audio-xai/experiments/objective_1_2/src/xai/objective2_ig_diagnostics.py", line 69, in <module>
    faithfulness_scores = load_faithfulness_scores("experiments/objective_1_2/obj2/zero_per_sample/metrics/xai_results_zero_per_sample.json")
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mqa887/audio-xai/experiments/objective_1_2/src/xai/objective2_ig_diagnostics.py", line 32, in load_faithfulness_scores
    with open(json_path, 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'experiments/objective_1_2/obj2/zero_per_sample/metrics/xai_results_zero_per_sample.json'
